Adding support for Windows
rticommunity/rticonnextdds-gateway pull request #4
Opened 2021-02-26 17:11 UTC by angelrti

this PR is for #3

2021-02-28 12:55 UTC, fgaranda commented on plugins/adapters/modbus/srcCxx/ModbusAdapterConfiguration.cxx
> +                        (long double)((int8_t) value),
static_cast<int8_t>(value)

2021-02-28 13:05 UTC, fgaranda requested changes
@angelrti I've just seen a couple of C-style casts that could be replaced with `static_cast`s. Other than that, everything looks good.

One thing I've realized is that the project assumes C99 support. Should we set this explicitly this requirement using CMake using `CMAKE_C_STANDARD`? Maybe that'd preclude us from building in VS < 2015, I don't know.

2021-03-03 10:46 UTC, angelrti commented
> @angelrti I've just seen a couple of C-style casts that could be replaced with `static_cast`s. Other than that, everything looks good.
> 
> One thing I've realized is that the project assumes C99 support. Should we set this explicitly this requirement using CMake using `CMAKE_C_STANDARD`? Maybe that'd preclude us from building in VS < 2015, I don't know.

We already set `CMAKE_C_STANDARD` to use C99 in the main CMakeLists https://github.com/rticommunity/rticonnextdds-gateway/blob/master/CMakeLists.txt

2021-03-03 12:26 UTC, angelrti commented on plugins/adapters/modbus/srcCxx/ModbusAdapterConfiguration.cxx
> +                        (long double)((int8_t) value),
done

2021-03-05 11:32 UTC, fgaranda approved these changes

2021-03-05 11:34 UTC, merged